### ISSUE TITLE
Bug: Inconsistent behaviour with library(pkg) and library("pkg")

### ISSUE THREAD

**Issue by ppoyk** [brshallo/funspotr#18]
It appears as if the function spot_funs_files (and likely other spot_* functions) are not able to identify the originating package for a function if it has been loaded in a script using `library("pkg")` function call, even though including the quotes is also a correct form.

When the library call was changed to `library(pkg)`, the pkgs-column in the table produced by the code below was correctly populated, and didn't contain fields with an `(unknown)` -value

My code to check for depencencies was the following:
```
tmp <- funspotr::list_files_wd(here::here())
deps <- funspotr::spot_funs_files(tmp[1:4, 2])
deps <- funspotr::unnest_results(deps)
View(deps)
```

**Comment by brshallo** [comment]
Thanks, should be fixed with 0dea59f
